services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cont-reportespiolis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/compartido:/mnt/compartido:ro
      - reportes_db:/app/src/basedatos
    networks:
      - edge_net

volumes:
  reportes_db:

networks:
  edge_net:
    external: true
