services:
  app:
    image: cont-reportespiolis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reportespiolis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - /mnt/compartido:/mnt/compartido:ro
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "127.0.0.1:3001:3000"
